/**
 * Company Agent Directory
 *
 * Pre-loaded directory of all 54 company agents, CSRs, EAs, Sales, Managers,
 * and Support team members for Alsop Coverage Check Now platform.
 */

export interface CompanyAgent {
    nickname: string;
    fullName: string;
    email: string;
    team: 'CSR' | 'EA' | 'Sales' | 'Managers' | 'Support' | 'Other';
    office: 'CH' | 'MCM' | 'RC' | 'MB' | '' | string;
    role: 'agent' | 'admin';
    active: boolean;
    agencyZoomName?: string;
    hearsayName?: string;
    ringCentralName?: string;
    ricochetName?: string;
    dashNbName?: string;
    quotesCodeName?: string;
}

export const COMPANY_AGENTS: CompanyAgent[] = [
    // ── CSR Team ──
    {
        nickname: 'Alex',
        fullName: 'Alex Clancy',
        email: 'alexclancy@allstate.com',
        team: 'CSR',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Alex Clancy',
        hearsayName: 'ALEX CLANCY',
        ringCentralName: 'Alex Clancy',
        dashNbName: 'ALEX CLANCY',
        quotesCodeName: '387-ALEX CLANCY',
    },
    {
        nickname: 'Alexandra',
        fullName: 'Alexandra Quintana',
        email: 'aquintana3@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Alexandra Quintana',
        hearsayName: 'ALEXANDRA QUINTANA',
        ringCentralName: 'Alexandra Quintana',
        dashNbName: 'ALEXANDRA QUINTANA',
        quotesCodeName: '722-ALEXANDRA QUINTANA',
    },
    {
        nickname: 'Ariana',
        fullName: 'Ariana Crawford',
        email: 'acrawford11@allstate.com',
        team: 'CSR',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Ariana Crawford',
        hearsayName: 'ARIANA CRAWFORD',
        ringCentralName: 'Ariana Crawford',
        ricochetName: 'Ariana Crawford',
        dashNbName: 'ARIANA CRAWFORD',
        quotesCodeName: '892-ARIANA CRAWFORD',
    },
    {
        nickname: 'Dawn',
        fullName: 'Dawn Zenor',
        email: 'dawnzenor@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Dawn Zenor',
        hearsayName: 'DAWN ZENOR',
        ringCentralName: 'Dawn Zenor',
        dashNbName: 'DAWN ZENOR',
        quotesCodeName: '618-DAWN ZENOR',
    },
    {
        nickname: 'Denice',
        fullName: 'Denice Santos',
        email: 'denicesantos@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Denice Santos',
        hearsayName: 'DENICE SANTOS',
        ringCentralName: 'Denice Santos',
        ricochetName: 'Denice Santos',
        dashNbName: 'DENICE SANTOS',
        quotesCodeName: '373-DENICE SANTOS',
    },
    {
        nickname: 'Estela',
        fullName: 'Estela Montalvo',
        email: 'emontalvo2@allstate.com',
        team: 'CSR',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Estela  Montalvo',
        hearsayName: 'ESTELA MONTALVO',
        ringCentralName: 'Estela Montalvo',
        dashNbName: 'ESTELA MONTALVO',
        quotesCodeName: '518-ESTELA MONTALVO',
    },
    {
        nickname: 'Gabby',
        fullName: 'Gabby Davis',
        email: 'carmendavis@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Gabby Davis',
        hearsayName: 'CARMEN DAVIS',
        ringCentralName: 'Gabby Davis',
        dashNbName: 'CARMEN DAVIS',
        quotesCodeName: '720-GABBY DAVIS',
    },
    {
        nickname: 'Isabel',
        fullName: 'Isabel Torres',
        email: 'isabeltorres1@allstate.com',
        team: 'CSR',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Isabel Torres',
        hearsayName: 'ISABEL TORRES',
        ringCentralName: 'Isabel Torres',
        dashNbName: 'ISABEL TORRES',
        quotesCodeName: '193-ISABEL TORRES',
    },
    {
        nickname: 'Jerome',
        fullName: 'Jerome Delfin',
        email: 'jeromedelfin@allstate.com',
        team: 'CSR',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Jerome Delfin',
        hearsayName: 'JEROME DELFIN',
        ringCentralName: 'Jerome Delfin',
        dashNbName: 'JEROME DELFIN',
        quotesCodeName: '863-JEROME DELFIN',
    },
    {
        nickname: 'Jose',
        fullName: 'Jose Huerta',
        email: 'josehuerta@allstate.com',
        team: 'CSR',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Jose Huerta',
        hearsayName: 'JOSE HUERTA',
        ringCentralName: 'Jose Huerta',
        dashNbName: 'JOSE HUERTA',
        quotesCodeName: '103-JOSE HUERTA',
    },
    {
        nickname: 'Juanita',
        fullName: 'Juanita Calderon',
        email: 'juanacalderon@allstate.com',
        team: 'CSR',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Juanita Calderon',
        hearsayName: 'JUANA CALDERON',
        ringCentralName: 'Juanita Calderon',
        ricochetName: 'Juanita Calderon',
        dashNbName: 'JUANA CALDERON',
        quotesCodeName: '757-JUANA CALDERON',
    },
    {
        nickname: 'Liliana',
        fullName: 'Liliana Morales',
        email: 'lmorales4@allstate.com',
        team: 'CSR',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Liliana Morales',
        hearsayName: 'LILIANA MORALES',
        ringCentralName: 'Liliana Morales',
        dashNbName: 'LILIANA MORALES',
        quotesCodeName: '092-LILIANA MORALES',
    },
    {
        nickname: 'Lori',
        fullName: 'Lori Ohlhauser',
        email: 'lohlhauser@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Lori Ohlhauser',
        hearsayName: 'LORI OHLHAUSER',
        ringCentralName: 'Lori Ohlhauser',
        dashNbName: 'LORI OHLHAUSER',
        quotesCodeName: '229-LORI OHLHAUSER',
    },
    {
        nickname: 'Maila',
        fullName: 'Maila Castro',
        email: 'mailacastro@allstate.com',
        team: 'CSR',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Maila Castro',
        hearsayName: 'MAILA CASTRO',
        ringCentralName: 'Maila Castro',
        ricochetName: 'Maila Castro',
        dashNbName: 'MAILA CASTRO',
        quotesCodeName: '327-MAILA CASTRO',
    },
    {
        nickname: 'Nancy',
        fullName: 'Nancy Gutierrez',
        email: 'ngutierrez5@allstate.com',
        team: 'CSR',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Nancy Gutierrez',
        hearsayName: 'NANCY GUTIERREZ',
        ringCentralName: 'Nancy Gutierrez',
        dashNbName: 'NANCY GUTIERREZ',
        quotesCodeName: '860-NANCY GUTIERREZ',
    },
    {
        nickname: 'Rosie',
        fullName: 'Rosario Delgado',
        email: 'rdelgado@allstate.com',
        team: 'CSR',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Rosie Delgado',
        hearsayName: 'ROSARIO DELGADO',
        ringCentralName: 'Rosie Delgado',
        dashNbName: 'ROSARIO DELGADO',
        quotesCodeName: '051-ROSARIO DELGADO',
    },
    {
        nickname: 'Teyssy',
        fullName: 'Teyssy Espino',
        email: 'teyssyespino1@allstate.com',
        team: 'CSR',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Teyssy Espino',
        hearsayName: 'Teyssy Espino',
        ringCentralName: 'Teyssy Espino',
    },

    // ── EA Team ──
    {
        nickname: 'Christine',
        fullName: 'Christine Lansing',
        email: 'clansing3@allstate.com',
        team: 'EA',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Christine Lansing',
        hearsayName: 'CHRISTINE LANSING',
        ricochetName: 'Christine Lansing',
        dashNbName: 'CHRISTINE LANSING',
        quotesCodeName: '278-CHRISTINE LANSING',
    },
    {
        nickname: 'Gilda',
        fullName: 'Gilda Aquino',
        email: 'gildaaquino2@allstate.com',
        team: 'EA',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Gilda Aquino',
        hearsayName: 'BRIGILDA AQUINO',
        ricochetName: 'Gilda Aquino',
        dashNbName: 'BRIGILDA AQUINO',
        quotesCodeName: '302-BRIGILDA AQUINO',
    },
    {
        nickname: 'Giselle',
        fullName: 'Giselle Ramos',
        email: 'giselleramos@allstate.com',
        team: 'EA',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Giselle Ramos',
        hearsayName: 'GISELLE RAMOS',
        ricochetName: 'Giselle Ramos',
        dashNbName: 'GISELLE RAMOS',
        quotesCodeName: '879-GISELLE RAMOS',
    },
    {
        nickname: 'Misty',
        fullName: 'Misty Torrez',
        email: 'mistytorrez1@allstate.com',
        team: 'EA',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Misty Torrez',
        hearsayName: 'MISTY TORREZ',
        ricochetName: 'Misty Torrez',
        dashNbName: 'MISTY TORREZ',
        quotesCodeName: '350-MISTY TORREZ',
    },
    {
        nickname: 'Roxana',
        fullName: 'Roxana Topete',
        email: 'roxanatopete1@allstate.com',
        team: 'EA',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Roxana Topete',
        hearsayName: 'ROXANA TOPETE',
        ricochetName: 'Roxana Topete',
        dashNbName: 'ROXANA TOPETE',
        quotesCodeName: '275-ROXANA TOPETE',
    },
    {
        nickname: 'Suzanne',
        fullName: 'Suzanne Yniguez',
        email: 'syniguez@allstate.com',
        team: 'EA',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Suzanne Yniguez',
        hearsayName: 'SUZANNE YNIGUEZ',
        ricochetName: 'Suzanne Yniguez',
        dashNbName: 'SUZANNE YNIGUEZ',
        quotesCodeName: '005-SUZANNE YNIGUEZ',
    },
    {
        nickname: 'Sylvia',
        fullName: 'Sylvia Duran',
        email: 'sylviaduran@allstate.com',
        team: 'EA',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Sylvia Duran',
        hearsayName: 'SYLVIA DURAN',
        ricochetName: 'Sylvia Duran',
        dashNbName: 'SYLVIA DURAN',
        quotesCodeName: '121-SYLVIA DURAN',
    },

    // ── Managers ──
    {
        nickname: 'Eric Alsop',
        fullName: 'Eric Alsop',
        email: 'ericalsop@allstate.com',
        team: 'Managers',
        office: 'MCM',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Greg Alsop',
        fullName: 'Greg Alsop',
        email: 'gregalsop@allstate.com',
        team: 'Managers',
        office: '',
        role: 'agent',
        active: true,
    },
    {
        nickname: 'Jennifer Martinez',
        fullName: 'Jennifer Martinez',
        email: 'jmartinez36@allstate.com',
        team: 'Managers',
        office: 'RC',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'John Paul Dizon',
        fullName: 'John Paul Dizon',
        email: 'johndizon2@allstate.com',
        team: 'Managers',
        office: 'CH',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Nancy Maldonado',
        fullName: 'Nancy Maldonado',
        email: 'nmaldonado@allstate.com',
        team: 'Managers',
        office: '',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Ric Becerra',
        fullName: 'Ric Becerra',
        email: 'rbecerra@allstate.com',
        team: 'Managers',
        office: '',
        role: 'admin',
        active: true,
    },

    // ── Sales Team ──
    {
        nickname: 'Charmaine',
        fullName: 'Charmaine Carrillo',
        email: 'ccarrillo16@allstate.com',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Charmaine Carrillo',
        hearsayName: 'CHARMAINE CARRILLO',
        ricochetName: 'Charmaine Carrillo',
        dashNbName: 'CHARMAINE CARRILLO',
        quotesCodeName: '077-CHARMAINE CARRILLO',
    },
    {
        nickname: 'Chris',
        fullName: 'Chris Elliott',
        email: 'chriselliott3@allstate.com',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: true,
        agencyZoomName: 'Chris Elliott',
        hearsayName: 'CHRIS ELLIOTT',
        ricochetName: 'Chris Elliott',
        dashNbName: 'CHRIS ELLIOTT',
        quotesCodeName: '035-CHRIS ELLIOTT',
    },
    {
        nickname: 'Christian',
        fullName: 'Christian Reyes',
        email: 'creyes9@allstate.com',
        team: 'Sales',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Christian Reyes',
        hearsayName: 'CHRISTIAN REYES',
        ricochetName: 'Christian Reyes',
        dashNbName: 'CHRISTIAN REYES',
        quotesCodeName: '188-CHRISTIAN REYES',
    },
    {
        nickname: 'Claudia',
        fullName: 'Claudia Sambrano',
        email: 'csambrano3@allstate.com',
        team: 'Sales',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Claudia Sambrano',
        hearsayName: 'CLAUDIA SAMBRANO',
        ricochetName: 'Claudia Sambrano',
        dashNbName: 'CLAUDIA SAMBRANO',
        quotesCodeName: '043-CLAUDIA SAMBRANO',
    },
    {
        nickname: 'Danny',
        fullName: 'Danny Bonilla',
        email: 'dannybonilla7@allstate.com',
        team: 'Sales',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Danny Bonilla',
        hearsayName: 'MARLON BONILLA',
        ricochetName: 'Danny Bonilla',
        dashNbName: 'MARLON BONILLA',
        quotesCodeName: '602-MARLON BONILLA',
    },
    {
        nickname: 'Eddie',
        fullName: 'Eddie Sanchez',
        email: 'hsanchez5@allstate.com',
        team: 'Sales',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Eddie Sanchez',
        hearsayName: 'HERIBERTO SANCHEZ',
        ricochetName: 'Eddie Sanchez',
        dashNbName: 'HERIBERTO JR SANCHEZ',
        quotesCodeName: '215-HERIBERTO JR SANCHEZ',
    },
    {
        nickname: 'Edwin',
        fullName: 'Edwin Sernas',
        email: 'edwinsernas@allstate.com',
        team: 'Sales',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Edwin Sernas',
        hearsayName: 'EDWIN SERNAS',
        ricochetName: 'Edwin Sernas',
        dashNbName: 'EDWIN SERNAS',
        quotesCodeName: '079-EDWIN SERNAS',
    },
    {
        nickname: 'Frank',
        fullName: 'Frank Villalobos',
        email: 'fvillalobos@allstate.com',
        team: 'Sales',
        office: 'CH',
        role: 'agent',
        active: true,
        agencyZoomName: 'Frank Villalobos',
        hearsayName: 'FRANK VILLALOBOS',
        ricochetName: 'Frank Villalobos',
        dashNbName: 'FRANK VILLALOBOS',
        quotesCodeName: '551-FRANK VILLALOBOS',
    },
    {
        nickname: 'Jenna',
        fullName: 'Jenna Zazueta',
        email: 'jennazazueta3@allstate.com',
        team: 'Sales',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Jenna Zazueta',
        hearsayName: 'JENNA ZAZUETA',
        ricochetName: 'Jenna Zazueta',
        dashNbName: 'JENNA ZAZUETA',
        quotesCodeName: '901-JENNA ZAZUETA',
    },
    {
        nickname: 'Myles',
        fullName: 'Myles Vinluan',
        email: 'mylesvinluan2@allstate.com',
        team: 'Sales',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Myles Vinluan',
        hearsayName: 'MYLES VINLUAN',
        ricochetName: 'Myles Vinluan',
        dashNbName: 'MYLES VINLUAN',
        quotesCodeName: '059-MYLES VINLUAN',
    },
    {
        nickname: 'Robert',
        fullName: 'Robert Lewis Jr',
        email: 'rlewisjr@allstate.com',
        team: 'Sales',
        office: 'MB',
        role: 'agent',
        active: true,
        agencyZoomName: 'Robert  Lewis Jr',
        hearsayName: 'ROBERT LEWIS',
        ricochetName: 'Robert Lewis Jr',
        dashNbName: 'ROBERT LEWIS',
        quotesCodeName: '824-ROBERT LEWIS',
    },
    {
        nickname: 'Rosalba',
        fullName: 'Rosalba Lozano',
        email: 'rosalbalozano@allstate.com',
        team: 'Sales',
        office: 'RC',
        role: 'agent',
        active: true,
        agencyZoomName: 'Rosalba Lozano',
        hearsayName: 'ROSALBA LOZANO',
        ricochetName: 'Rosalba Lozano',
        dashNbName: 'ROSALBA LOZANO',
        quotesCodeName: '351-ROSALBA LOZANO',
    },
    {
        nickname: 'Zypher',
        fullName: 'Zypher',
        email: '',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: true,
    },

    // ── Support / Servicing Team ──
    {
        nickname: 'Charlie Paz',
        fullName: 'Charlie Paz',
        email: 'carlospaz@allstate.com',
        team: 'Support',
        office: 'MCM',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Danicah',
        fullName: 'Danicah',
        email: 'alsopva03@gmail.com',
        team: 'Support',
        office: '',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Paula',
        fullName: 'Paula',
        email: 'alsopva01@gmail.com',
        team: 'Support',
        office: '',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Phoebe',
        fullName: 'Phoebe',
        email: 'alsopva02@gmail.com',
        team: 'Support',
        office: '',
        role: 'admin',
        active: true,
    },
    {
        nickname: 'Phoebe Hernandez CCN',
        fullName: 'Phoebe Hernandez CCN',
        email: 'phoebe@coveragechecknow.com',
        team: 'Support',
        office: '',
        role: 'agent',
        active: true,
    },

    // ── Inactive Roster (Excluded from default active dispatch) ──
    {
        nickname: 'Danielle',
        fullName: 'Danielle Self',
        email: '',
        team: 'EA',
        office: 'MCM',
        role: 'agent',
        active: false,
    },
    {
        nickname: 'Angelina',
        fullName: 'Angelina Sandoval',
        email: '',
        team: 'Sales',
        office: 'RC',
        role: 'agent',
        active: false,
    },
    {
        nickname: 'Hrach',
        fullName: 'Hrach Kosyan',
        email: '',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: false,
    },
    {
        nickname: 'Jessie',
        fullName: 'Yessenia Pedroza-Chavez',
        email: '',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: false,
    },
    {
        nickname: 'Jonathan',
        fullName: 'Jonathan Jimenez',
        email: '',
        team: 'Sales',
        office: 'MB',
        role: 'agent',
        active: false,
    },
    {
        nickname: 'Rachel',
        fullName: 'Rachel Garcia',
        email: '',
        team: 'Sales',
        office: 'MCM',
        role: 'agent',
        active: false,
    },
];

/**
 * Returns all active agents with valid email addresses.
 */
export function getActiveAgents(): CompanyAgent[] {
    return COMPANY_AGENTS.filter(
        a => a.active && a.email && a.email !== '(None)' && a.email.includes('@')
    );
}

/**
 * Smart lookup by nickname, full name, or partial string.
 */
export function findAgentByName(nameOrQuery: string): CompanyAgent | null {
    if (!nameOrQuery) return null;
    const clean = nameOrQuery.toLowerCase().trim();

    return (
        COMPANY_AGENTS.find(
            a =>
                a.fullName.toLowerCase() === clean ||
                a.nickname.toLowerCase() === clean ||
                a.email.toLowerCase() === clean ||
                (a.quotesCodeName && a.quotesCodeName.toLowerCase().includes(clean))
        ) ||
        COMPANY_AGENTS.find(
            a =>
                a.fullName.toLowerCase().includes(clean) ||
                a.nickname.toLowerCase().includes(clean)
        ) ||
        null
    );
}

/**
 * Lookup agent by exact email address.
 */
export function getAgentByEmail(email: string): CompanyAgent | null {
    if (!email) return null;
    const clean = email.toLowerCase().trim();
    return COMPANY_AGENTS.find(a => a.email.toLowerCase() === clean) || null;
}
